/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const TRANSLATIONS = {
  en: {
    welcome: 'Welcome to CoreSaaS',
    tagline: 'Enterprise-grade identity and secure onboarding system.',
    login: 'Login',
    register: 'Register',
    googleLogin: 'Continue with Google',
    msLogin: 'Continue with Microsoft',
    phoneLogin: 'Continue with Phone',
    email: 'Email Address',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    or: 'OR',
    firstName: 'First Name',
    lastName: 'Last Name',
    mobile: 'Mobile Number',
    confirmPassword: 'Confirm Password',
    businessName: 'Business Name',
    businessType: 'Business Type',
    acceptTerms: 'I accept the Terms & Conditions and Privacy Policy',
    otpTitle: 'Verify OTP',
    otpDescription: 'Enter the 6-digit verification code sent to your email/phone.',
    verify: 'Verify',
    resend: 'Resend OTP',
    otpCountdown: 'Resend in {count}s',
    getOtp: 'Send OTP',
    onboardingTitle: 'Business Setup',
    step: 'Step',
    next: 'Next Step',
    previous: 'Previous Step',
    skip: 'Skip / Invite Later',
    complete: 'Complete Setup',
    businessInfo: 'Business Information',
    companyDetails: 'Company Details',
    logoUpload: 'Logo Upload',
    bankDetails: 'Bank Details',
    inviteTeam: 'Invite Team',
    successTitle: 'Setup Successful!',
    successDesc: 'Your enterprise portal is now ready. Redirecting to your dashboard placeholder...',
  },
  hi: {
    welcome: 'CoreSaaS में आपका स्वागत है',
    tagline: 'एंटरप्राइज-ग्रेड पहचान और सुरक्षित ऑनबोर्डिंग सिस्टम।',
    login: 'लॉगिन करें',
    register: 'रजिस्टर करें',
    googleLogin: 'गूगल के साथ जारी रखें',
    msLogin: 'माइक्रोसॉफ्ट के साथ जारी रखें',
    phoneLogin: 'फोन के साथ जारी रखें',
    email: 'ईमेल पता',
    password: 'पासवर्ड',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    dontHaveAccount: 'खाता नहीं है?',
    alreadyHaveAccount: 'पहले से ही खाता है?',
    or: 'अथवा',
    firstName: 'पहला नाम',
    lastName: 'अंतिम नाम',
    mobile: 'मोबाइल नंबर',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    businessName: 'व्यवसाय का नाम',
    businessType: 'व्यवसाय का प्रकार',
    acceptTerms: 'मैं नियम और शर्तें और गोपनीयता नीति स्वीकार करता हूं',
    otpTitle: 'ओटीपी सत्यापित करें',
    otpDescription: 'अपने ईमेल/फोन पर भेजे गए 6-अंकीय सत्यापन कोड को दर्ज करें।',
    verify: 'सत्यापित करें',
    resend: 'ओटीपी पुनः भेजें',
    otpCountdown: '{count} सेकंड में पुनः भेजें',
    getOtp: 'ओटीपी भेजें',
    onboardingTitle: 'व्यवसाय सेटअप',
    step: 'कदम',
    next: 'अगला कदम',
    previous: 'पिछला कदम',
    skip: 'छोड़ें / बाद में आमंत्रित करें',
    complete: 'सेटअप पूरा करें',
    businessInfo: 'व्यावसायिक जानकारी',
    companyDetails: 'कंपनी का विवरण',
    logoUpload: 'लोगो अपलोड',
    bankDetails: 'बैंक विवरण',
    inviteTeam: 'टीम आमंत्रित करें',
    successTitle: 'सेटअप सफल रहा!',
    successDesc: 'आपका एंटरप्राइज पोर्टल अब तैयार है। डैशबोर्ड पर रीडायरेक्ट किया जा रहा है...',
  },
  es: {
    welcome: 'Bienvenido a CoreSaaS',
    tagline: 'Sistema de identidad de nivel empresarial y registro seguro.',
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    googleLogin: 'Continuar con Google',
    msLogin: 'Continuar con Microsoft',
    phoneLogin: 'Continuar con Teléfono',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    rememberMe: 'Recordarme',
    forgotPassword: '¿Olvidaste tu contraseña?',
    dontHaveAccount: '¿No tienes una cuenta?',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    or: 'O',
    firstName: 'Nombre',
    lastName: 'Apellido',
    mobile: 'Número de Móvil',
    confirmPassword: 'Confirmar Contraseña',
    businessName: 'Nombre de la Empresa',
    businessType: 'Tipo de Negocio',
    acceptTerms: 'Acepto los Términos y Condiciones y la Política de Privacidad',
    otpTitle: 'Verificar OTP',
    otpDescription: 'Ingrese el código de verificación de 6 dígitos enviado a su correo/teléfono.',
    verify: 'Verificar',
    resend: 'Reenviar OTP',
    otpCountdown: 'Reenviar en {count}s',
    getOtp: 'Enviar OTP',
    onboardingTitle: 'Configuración Comercial',
    step: 'Paso',
    next: 'Siguiente Paso',
    previous: 'Paso Anterior',
    skip: 'Omitir / Invitar más tarde',
    complete: 'Completar Configuración',
    businessInfo: 'Información del Negocio',
    companyDetails: 'Detalles de la Compañía',
    logoUpload: 'Carga de Logo',
    bankDetails: 'Detalles Bancarios',
    inviteTeam: 'Invitar Equipo',
    successTitle: '¡Configuración Exitosa!',
    successDesc: 'Su portal empresarial ya está listo. Redirigiendo al marcador de posición del panel...',
  },
  zh: {
    welcome: '欢迎来到 CoreSaaS',
    tagline: '企业级身份与安全入驻系统。',
    login: '登录',
    register: '注册',
    googleLogin: '使用 Google 账号继续',
    msLogin: '使用 Microsoft 账号继续',
    phoneLogin: '使用手机号继续',
    email: '电子邮箱',
    password: '密码',
    rememberMe: '记住我',
    forgotPassword: '忘记密码？',
    dontHaveAccount: '还没有账号？',
    alreadyHaveAccount: '已有账号？',
    or: '或',
    firstName: '名字',
    lastName: '姓氏',
    mobile: '手机号码',
    confirmPassword: '确认密码',
    businessName: '企业名称',
    businessType: '业务类型',
    acceptTerms: '我接受条款和条件及隐私政策',
    otpTitle: '验证 OTP',
    otpDescription: '输入发送到您的邮箱/手机的 6 位数验证码。',
    verify: '验证',
    resend: '重新发送 OTP',
    otpCountdown: '{count}秒后重发',
    getOtp: '发送验证码',
    onboardingTitle: '业务设置',
    step: '步骤',
    next: '下一步',
    previous: '上一步',
    skip: '跳过 / 稍后邀请',
    complete: '完成设置',
    businessInfo: '企业信息',
    companyDetails: '公司详情',
    logoUpload: '上传 Logo',
    bankDetails: '银行详情',
    inviteTeam: '邀请团队',
    successTitle: '设置成功！',
    successDesc: '您的企业门户现已准备就绪。正在重定向到您的仪表板占位符...',
  }
};

export const LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'hi', label: 'हिन्दी', flag: '🇮🇳' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'zh', label: '中文', flag: '🇨🇳' },
];
